### ISSUE TITLE
Thank you great bot, I am really happy

### ISSUE THREAD

**Issue by limter1** [Helvio88/wa-stickerbot#1]
Thank you great bot, I am really happy

.

I am facing a problem when sending a picture or video that sends a 2 stickers

**Comment by Helvio88** [comment]
Latest patch resolved it. Removed `onMessage` in favor of `onAnyMessage`. Please update and enjoy!

**Comment by limter1** [comment]
You have tried the update
does not work

https://up4net.com/uploads3/up4net-%D9%84%D9%82%D8%B7%D8%A9-%D8%B4%D8%A7%D8%B4%D8%A9-%D9%85%D9%86-2021-02-13-02-19-24.png

Does not respond

**Comment by Helvio88** [comment]
Let me suggest you delete and re-clone the whole repository. That would probably fix it.
Additionally, you might want to change the index.ts / index.js file. The latest version only creates stickers to group chats!

**Comment by limter1** [comment]
I deleted and re-cloned the entire repository but when sending a video or image that does not respond
I tried it on linux or windows 10

**Comment by limter1** [comment]
Very sorry it works
Only in groups
It is better than before
Thank you thank you thank you

**Comment by limter1** [comment]
You have to write the name for me pack or  author
The sticker does not work
Example

    author: 'Bot ⭐',
    pack: 'limter 🤖',
   
https://k.top4top.io/p_1872rec9h0.jpg
